# Generated by Django 5.1.1 on 2024-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='patient',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
